stages:
  - build
  - deploy

image: docker:20.10.5

services:
  - docker:20.10.5-dind

before_script:
  - echo "$DOCKER_PASS" | docker login --username "$DOCKER_USERNAME" --password-stdin

build_image:
  stage: build
  script:
    - docker build -t uworkback/uwork-api:$(cat version.txt) .

push_image:
  stage: deploy
  script:
    - docker push uworkback/uwork-api:$(cat version.txt)